# Generated by Django 5.1.3 on 2024-12-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sms_code",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_referral",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_referral",
                to="users.referral",
                to_field="referral",
                verbose_name="Реферальная ссылка",
            ),
        ),
    ]
