# Generated by Django 5.1.3 on 2024-12-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_user_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="self_referral",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="self_referral",
                to="users.referral",
                to_field="referral",
                verbose_name="Реферал",
            ),
        ),
    ]
