# Generated by Django 5.1.3 on 2024-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_sms_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sms_code",
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
