# Generated by Django 5.1.3 on 2025-01-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_self_referral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_referral",
                to="users.referral",
                to_field="referral",
                verbose_name="Реферальная ссылка",
            ),
        ),
    ]
